server:
  port: 8087
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

canal.conf:
  mode: tcp # kafka rocketMQ
  canalServerHost: 172.16.0.252:11111
  #  zookeeperHosts: slave1:2181
  #  mqServers: 127.0.0.1:9092 #or rocketmq
  #  flatMessage: true
  batchSize: 500
  syncBatchSize: 1000
  retries: 0
  timeout:
  accessKey:
  secretKey:
  srcDataSources:
    ngpDS:
      url: jdbc:mysql://172.17.0.232:3357/ngp_erptable?useUnicode=true
      username: dev_ngp
      password: grasp147-
  canalAdapters:
    - instance: ngp # canal instance Name or mq topic name
      groups:
        - groupId: g1
          outerAdapters:
            - name: logger
            - name: rdb
              key: ck-ngp
              properties:
                jdbc.driverClassName: ru.yandex.clickhouse.ClickHouseDriver
                jdbc.url: jdbc:clickhouse://172.17.1.98:8123/ngp_erptable
                jdbc.username: ngp
                jdbc.password: 1c9M3Ic7
            - name: rdb
              key: greenplum-ngp
              properties:
                jdbc.driverClassName: ru.yandex.clickhouse.ClickHouseDriver
                jdbc.url: jdbc:pivotal:greenplum://127.0.0.1:5432;DatabaseName=ngp_erptable
                jdbc.username: ngp
                jdbc.password: grasp147+
            - name: rdb
              key: gp-ngp
              properties:
                jdbc.driverClassName: org.postgresql.Driver
                jdbc.url: jdbc:postgresql://172.17.1.63:5432/ngp_temp
                jdbc.username: gpadmin
                jdbc.password: gpadmin
